version: "3.4"
services:
  web:
    build: .
    environment:
      - PORT=999
      - HOST="0.0.0.0"
    ports:
      - "5000:5000"
  app:
    image: "wym_project"
    volumes:
      - "./:/app"
    links:
      - db

    
  db:
    image: postgres
    ports: 
      - "5000:5000"
    volumes:
      - ./dataset:/dataset
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DATABASE: todos
